### ISSUE TITLE
CRDT: Tracking

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#11]
- [x] [Map CRDTs on top of IPLD](https://github.com/ipfs/dynamic-data-and-capabilities/issues/1)
- [x] [Garbage Collection](https://github.com/ipfs/dynamic-data-and-capabilities/issues/2)
- [x] [CRDT over IPLD Performance](https://github.com/ipfs/dynamic-data-and-capabilities/issues/3)
- [x] [CRDT persistence](https://github.com/ipfs/dynamic-data-and-capabilities/issues/10)
- [x] [CRDT: identify authorship](https://github.com/ipfs/dynamic-data-and-capabilities/issues/12)

**Comment by fritzy** [comment]
The above links are not working.

**Comment by pgte** [comment]
@fritzy thanks for reporting, should be fixed now.
